In [1]:
import torch
import numpy as np

In [2]:
data = [[1, 2], [3, 4]]
x_data = torch.tensor(data)
print(f"direct way: \n {x_data} \n")
np_array = np.array(data)
x_np = torch.from_numpy(np_array)
print(f"from numpy: \n {x_np} \n")

direct way: 
 tensor([[1, 2],
        [3, 4]]) 

from numpy: 
 tensor([[1, 2],
        [3, 4]], dtype=torch.int32) 



In [3]:
x_ones = torch.ones_like(x_data)
print(f"ones tensor: \n {x_ones} \n")
x_rand = torch.rand_like(x_data, dtype=torch.float)
print(f"random tensor: \n {x_rand} \n")

ones tensor: 
 tensor([[1, 1],
        [1, 1]]) 

random tensor: 
 tensor([[0.1751, 0.8209],
        [0.3757, 0.1573]]) 



In [4]:
shape = (2, 4, 3)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)
print(f"random tensor: \n {rand_tensor} \n")
print(f"ones tensor: \n {ones_tensor} \n")
print(f"zeros tensor: \n {zeros_tensor} \n")

random tensor: 
 tensor([[[0.7493, 0.6785, 0.2943],
         [0.5479, 0.7541, 0.3755],
         [0.2787, 0.5804, 0.4185],
         [0.1158, 0.7734, 0.4400]],

        [[0.8427, 0.5336, 0.3644],
         [0.6091, 0.3661, 0.2896],
         [0.0366, 0.5144, 0.5603],
         [0.3909, 0.8747, 0.6966]]]) 

ones tensor: 
 tensor([[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]]) 

zeros tensor: 
 tensor([[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]]) 



In [5]:
tensor = torch.rand(3, 4)
print(f"shape of tensor: {tensor.shape}")
print(f"datatype of tensor: {tensor.dtype}")
print(f"device tensor is stored on: {tensor.device}")

shape of tensor: torch.Size([3, 4])
datatype of tensor: torch.float32
device tensor is stored on: cpu


In [6]:
if torch.cuda.is_available():
    tensor = tensor.to("cuda")
    print(f"device tensor is stored on: {tensor.device}")

In [7]:
tensor = torch.tensor([[1, 2], [3, 4]])
tensor[:, 1] = 0
print(tensor)

tensor([[1, 0],
        [3, 0]])


In [8]:
tensor = torch.tensor([[1, 2], [3, 4]])
t1 = torch.cat([tensor, tensor, tensor], dim=1)
t2 = torch.cat([tensor, tensor, tensor], dim=0)
print(t1)
print(t2)


tensor([[1, 2, 1, 2, 1, 2],
        [3, 4, 3, 4, 3, 4]])
tensor([[1, 2],
        [3, 4],
        [1, 2],
        [3, 4],
        [1, 2],
        [3, 4]])


In [9]:
t3 = torch.stack([tensor, tensor, tensor, tensor], dim=1)
t4 = torch.stack([tensor, tensor, tensor, tensor], dim=0)
t5 = torch.stack([tensor, tensor, tensor, tensor], dim=2)
print(t3, t3.shape)
print('\n')
print(t4, t4.shape)
print('\n')
print(t5, t5.shape)

tensor([[[1, 2],
         [1, 2],
         [1, 2],
         [1, 2]],

        [[3, 4],
         [3, 4],
         [3, 4],
         [3, 4]]]) torch.Size([2, 4, 2])


tensor([[[1, 2],
         [3, 4]],

        [[1, 2],
         [3, 4]],

        [[1, 2],
         [3, 4]],

        [[1, 2],
         [3, 4]]]) torch.Size([4, 2, 2])


tensor([[[1, 1, 1, 1],
         [2, 2, 2, 2]],

        [[3, 3, 3, 3],
         [4, 4, 4, 4]]]) torch.Size([2, 2, 4])


In [10]:
print(f"tensor.mul(tensor): \n {tensor.mul(tensor)} \n")
print(f"tensor * tensor: \n {tensor * tensor} \n")

tensor.mul(tensor): 
 tensor([[ 1,  4],
        [ 9, 16]]) 

tensor * tensor: 
 tensor([[ 1,  4],
        [ 9, 16]]) 



In [11]:
print(f"tensor.matmul(tensor): \n {tensor.matmul(tensor)} \n")
print(f"tensor @ tensor: \n {tensor @ tensor} \n")

tensor.matmul(tensor): 
 tensor([[ 7, 10],
        [15, 22]]) 

tensor @ tensor: 
 tensor([[ 7, 10],
        [15, 22]]) 



In [12]:
print(tensor, "\n")
tensor.add_(5)
print(tensor)

tensor([[1, 2],
        [3, 4]]) 

tensor([[6, 7],
        [8, 9]])


In [13]:
t = torch.ones(5)
print(f"t: {t}")
n = t.numpy()
print(f"n: {n}")

t: tensor([1., 1., 1., 1., 1.])
n: [1. 1. 1. 1. 1.]


In [14]:
t.add_(1)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.])
n: [2. 2. 2. 2. 2.]


In [15]:
n = np.ones(5)
t = torch.from_numpy(n)
print(f"n: {t}")
print(f"t: {n}")

n: tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
t: [1. 1. 1. 1. 1.]


In [16]:
np.add(n, 1, out=n)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
n: [2. 2. 2. 2. 2.]
